# Generated by Django 5.0.4 on 2024-04-17 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tag_created_at_tag_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
    ]
