# Generated by Django 4.2.11 on 2024-05-09 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_answer_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='Cat03.jpg', null=True, upload_to='avatar/%Y/%m/%d')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='Cat03.jpg', null=True, upload_to='avatar/%Y/%m/%d')),
                ('groups', models.ManyToManyField(to='app.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('accessible_groups', models.ManyToManyField(to='app.group')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='answerlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='answerlike',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answerlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='questionlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='questionlike',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionlike',
            name='user',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='AnswerLike',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionLike',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
