# Generated by Django 4.2.11 on 2024-05-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_group_student_teacher_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='groups',
        ),
        migrations.AddField(
            model_name='teacher',
            name='can_create_tests',
            field=models.BooleanField(default=True),
        ),
    ]
