# Generated by Django 4.2.11 on 2024-05-16 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_submissionattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionattempt',
            name='submission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.submission'),
            preserve_default=False,
        ),
    ]
