# Generated by Django 4.2.11 on 2024-05-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_submissionattempt_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='score',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='start_time',
        ),
        migrations.AddField(
            model_name='testresult',
            name='correct_answers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='incorrect_answers_count',
            field=models.IntegerField(default=0),
        ),
    ]
