# Generated by Django 4.2.11 on 2024-05-16 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_testresult_end_time_remove_testresult_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
    ]
