# Generated by Django 4.2.11 on 2024-05-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_question_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestparticipant',
            name='best_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submissionattempt',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
