# Generated by Django 4.2.11 on 2024-05-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_contestparticipant_best_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestparticipant',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
