# Generated by Django 4.2.11 on 2024-05-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_contestparticipant_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='groups',
            field=models.ManyToManyField(related_name='teachers', to='app.group'),
        ),
    ]
